// react-app/src/components/users-list/UsersList.tsx
import React, { ChangeEvent } from "react";
import { IAccountsService } from "../../api-services/AccountsService";
import { IAppServicesFactory, _IAppServicesFactory } from "../../AppServicesFactory";
import { User } from "../../models/user";
import { OrderingRule } from "../../ServiceQueries/OrderingRule";
import { PagingRule, SearchRule } from "../../ServiceQueries/SearchRule";
import { UserQuery } from "../../ServiceQueries/UserQuery";

interface UsersListStateData {
  users: User[];
  orderByIdDesc: boolean;
  orderByUserNameDesc: boolean;
  orderByActiveDesc: boolean;
  byIdField: number | "";
  byUsernameField: string;
  byActiveField: boolean;
  byInactiveField: boolean;
  [key: string]: any;
}

interface UsersListPropsData {}

export class UsersList extends React.Component<UsersListPropsData, UsersListStateData>{
    private servicesFactory: IAppServicesFactory = _IAppServicesFactory();     
    private accountsService: IAccountsService = this.servicesFactory.IAccountsService;
    
    constructor(props: UsersListPropsData) {
        super(props);

        this.state = {
            users: [],
            byActiveField: false,
            byIdField: "",
            byInactiveField: false,
            byUsernameField: "",
            orderByActiveDesc: false,
            orderByIdDesc: false,
            orderByUserNameDesc: false
        };
    }

    componentDidMount(){
        this.accountsService.Get().subscribe(result => {
            if(result){
                this.setState({ users: result });
            }
        });
    }

    OrderById(){
        this.setState(
            {
                orderByUserNameDesc: false,
                orderByActiveDesc: false
            }, 
            () => {            
                const ordering_rules: OrderingRule[] = [{ fieldName: "ID", isDescending: this.state.orderByIdDesc }];
                const query: UserQuery = { ordering_rules: ordering_rules, search_rules: [] };
                this.accountsService.GetBy(query).subscribe(result => {
                    if(result){
                        this.setState((state) => ({
                            users: result,
                            orderByIdDesc: !state.orderByIdDesc
                        }))                        
                    }
                });
        });
    }

    OrderByUserName(){
        this.setState(
            {
                orderByIdDesc: false,
                orderByActiveDesc: false
            }, 
            () => {            
                const ordering_rules: OrderingRule[] = [{ isDescending: this.state.orderByUserNameDesc, fieldName: "UserName" }];
                const query: UserQuery = { ordering_rules: ordering_rules, search_rules: [] };
                this.accountsService.GetBy(query).subscribe(result => {
                    if(result){
                        this.setState((state) => ({
                            users: result,
                            orderByUserNameDesc: !state.orderByUserNameDesc
                        }))                        
                    }
                });
        });
    }

    OrderByActive(){
        this.setState(
            {
                orderByIdDesc: false,
                orderByUserNameDesc: false
            }, 
            () => {            
                const ordering_rules: OrderingRule[] = [{ isDescending: this.state.orderByActiveDesc, fieldName: "Active" }];
                const query: UserQuery = { ordering_rules: ordering_rules, search_rules: [] };
                this.accountsService.GetBy(query).subscribe(result => {
                    if(result){
                        this.setState((state) => ({
                            users: result,
                            orderByActiveDesc: !state.orderByActiveDesc
                        }))                        
                    }
                });
        });
    }

    ActiveChange(){
        if(this.state.byActiveField){            
            this.setState({
                byInactiveField: false
            });
        }

        this.FilterList();
    }

    InactiveChange(){
        if(this.state.byInactiveField){
            this.setState({
                byActiveField: false
            });            
        }

        this.FilterList();
    }
    
    FilterList(){
        setTimeout(() => {
            const ordering_rules: OrderingRule[] = [];
            let search_rules: SearchRule[] = [];
            const emptyPagingRule: PagingRule = { page:0, pageSize:0 };

            if(this.state.byIdField > 0) {
                search_rules.push({ condition: `ID == ${this.state.byIdField}`, pagingRule: emptyPagingRule });
            }

            if(this.state.byUsernameField){
                search_rules.push({ condition: `UserName.Contains("${this.state.byUsernameField}")`, pagingRule: emptyPagingRule });
            }

            if(this.state.byInactiveField){
                search_rules.push({ condition: `!Active`, pagingRule: emptyPagingRule });
            }

            if(this.state.byActiveField){
                search_rules.push({ condition: `Active`, pagingRule: emptyPagingRule });
            }

            const query: UserQuery = { ordering_rules: ordering_rules, search_rules: search_rules };
            this.accountsService.GetBy(query).subscribe(result => {
                if(result){
                    this.setState({
                        users: result
                    });                    
                }
            });
        }, 50);
    }

    handleChange = (e: ChangeEvent<HTMLInputElement>, callback: () => void) => {
        const { name, value } = e.target;        
        this.setState({ [name]: value }, callback);
    }

    handleCheckboxChange = (e: ChangeEvent<HTMLInputElement>, callback: () => void) => {
        const { name, checked } = e.target;
        this.setState({[name]: checked }, callback);
    }
    
    render(){
        return(
            <div className="w3-container w3-margin-top">
                <h2>Users List</h2>
                
                <table className="w3-table-all w3-card-4">
                    <tr>
                    <th>
                        <span className="w3-cursor-pointer" onClick={this.OrderById} >ID</span>
                        <input style={{marginLeft: "5px"}} type="number" name="byIdField" onChange={ (e: ChangeEvent<HTMLInputElement>) => this.handleChange(e, this.FilterList) } value={ this.state.byIdField } />
                    </th>
                    <th>
                        <span className="w3-cursor-pointer" onClick={ this.OrderByUserName } >Username</span>
                        <input style={{marginLeft: "5px"}} type="text" name="byUsernameField" onChange={ (e: ChangeEvent<HTMLInputElement>) => this.handleChange(e, this.FilterList) } value={ this.state.byUsernameField } />
                    </th>
                    <th>
                        <input type="checkbox" id="user-active" name="byActiveField" onChange={ (e: ChangeEvent<HTMLInputElement>) => this.handleCheckboxChange(e, this.ActiveChange) } checked={ this.state.byActiveField } />
                        &nbsp;
                        <label htmlFor="user-active" >active</label>
                        &nbsp;
                        <input type="checkbox" id="user-inactive" name="byInactiveField" onChange={ (e: ChangeEvent<HTMLInputElement>) => this.handleCheckboxChange(e, this.InactiveChange) } checked={ this.state.byInactiveField } />
                        &nbsp;
                        <label htmlFor="user-inactive" >inactive</label>
                    </th>
                    </tr>
                    { this.state.users.map((user, key) => 
                        (
                        <tr key={key}>
                            <td>{user.id}</td>
                            <td>{user.username}</td>
                            <td>{user.active ? "Active" : "Inactive" }</td>
                        </tr>
                        )
                    )}
                </table>
            </div>
        );
    }
}

// BaseStartupProject.API/AngularApp/src/app/components/users-list/users-list.component.ts
import { Component, OnInit } from '@angular/core';
import { GlobalService } from 'src/app/global.service';
import { Router } from '@angular/router';
import { User } from '../../models/user';
import { AccountsService } from '../../api-services/accounts.service';
import { UserQuery } from 'src/app/ServiceQueries/UserQuery';
import { OrderingRule } from 'src/app/ServiceQueries/OrderingRule';
import { SearchRule, PagingRule } from 'src/app/ServiceQueries/SearchRule';

@Component({
  selector: 'app-users-list',
  templateUrl: './users-list.component.html',
  styleUrls: ['./users-list.component.css']
})
export class UsersListComponent implements OnInit {

  public users: User[];
  private orderByIdDesc: boolean = false;
  private orderByUserNameDesc: boolean = false;
  private orderByActiveDesc: boolean = false;

  public byIdField: number;
  public byUsernameField: string = "";
  public byActiveField: boolean = false;
  public byInactiveField: boolean = false;

  constructor(private router: Router, private global: GlobalService, private accountsService: AccountsService) { }

  ngOnInit() {
    if(!this.global.isUserLogedIn()){
      this.router.navigate(["/"]);
    } else {
      this.accountsService.Get().subscribe(result => {
        if(result){
          this.users = result;
        }
      });
    }
  }

  OrderById(){
    this.orderByUserNameDesc = false;
    this.orderByActiveDesc = false;

    const ordering_rules: OrderingRule[] = [{ fieldName: "ID", isDescending: this.orderByIdDesc }];
    const query: UserQuery = { ordering_rules: ordering_rules, search_rules: [] };
    this.accountsService.GetBy(query).subscribe(result => {
      if(result){
        this.users = result;
        this.orderByIdDesc = !this.orderByIdDesc;
      }
    });
  }

  OrderByUserName(){
    this.orderByIdDesc = false;
    this.orderByActiveDesc = false;

    const ordering_rules: OrderingRule[] = [{ isDescending: this.orderByUserNameDesc, fieldName: "UserName" }];
    const query: UserQuery = { ordering_rules: ordering_rules, search_rules: [] };
    this.accountsService.GetBy(query).subscribe(result => {
      if(result){
        this.users = result;
        this.orderByUserNameDesc = !this.orderByUserNameDesc;
      }
    });
  }

  OrderByActive(){
    this.orderByIdDesc = false;
    this.orderByUserNameDesc = false;

    const ordering_rules: OrderingRule[] = [{ isDescending: this.orderByActiveDesc, fieldName: "Active" }];
    const query: UserQuery = { ordering_rules: ordering_rules, search_rules: [] };
    this.accountsService.GetBy(query).subscribe(result => {
      if(result){
        this.users = result;
        this.orderByActiveDesc = !this.orderByActiveDesc;
      }
    });
  }

  ActiveChange(){
    if(this.byActiveField){
      this.byInactiveField = false;
    }

    this.FilterList();
  }

  InactiveChange(){
    if(this.byInactiveField){
      this.byActiveField = false;
    }

    this.FilterList();
  }

  FilterList(){
    setTimeout(() => {
      const ordering_rules: OrderingRule[] = [];
      let search_rules: SearchRule[] = new Array<SearchRule>();

      if(this.byIdField > 0) {
        search_rules.push({ condition: `ID == ${this.byIdField}`, paging_rule: new PagingRule() });
      }

      if(this.byUsernameField){
        search_rules.push({ condition: `UserName.Contains("${this.byUsernameField}")`, paging_rule: new PagingRule() });
      }

      if(this.byInactiveField){
        search_rules.push({ condition: `!Active`, paging_rule: new PagingRule() });
      }

      if(this.byActiveField){
        search_rules.push({ condition: `Active`, paging_rule: new PagingRule() });
      }

      const query: UserQuery = { ordering_rules: ordering_rules, search_rules: search_rules };
      this.accountsService.GetBy(query).subscribe(result => {
        if(result){
          this.users = result;
        }
      });
    }, 50);
  }
}

<div class="w3-container w3-margin-top">
  <h2>Table as a Card</h2>
  <p>The w3-card-* classes makes the table look like a card (adds shadows):</p>

  <table class="w3-table-all w3-card-4">
    <tr>
      <th>
        <span class="w3-cursor-pointer" (click)="OrderById()">ID</span>
        <input style="margin-left: 5px;" type="number" (change)="FilterList()" [(ngModel)]="byIdField" />
      </th>
      <th>
        <span class="w3-cursor-pointer" (click)="OrderByUserName()" >Username</span>
        <input style="margin-left: 5px;" type="text" (change)="FilterList()" [(ngModel)]="byUsernameField" />
      </th>
      <th>
          <input type="checkbox" id="user-active" (change)="byActiveField = !byActiveField; ActiveChange();" [checked]="byActiveField" />
          &nbsp;
          <label for="user-active" >active</label>
          &nbsp;
          <input type="checkbox" id="user-inactive" (change)="byInactiveField = !byInactiveField; InactiveChange();" [checked]="byInactiveField" />
          &nbsp;
          <label for="user-inactive" >inactive</label>
      </th>
    </tr>
    <tr *ngFor="let user of users">
      <td>{{user.id}}</td>
      <td>{{user.username}}</td>
      <td>{{user.active}}</td>
    </tr>
  </table>
</div>
