// angular-app/src/app/components/home/home.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
})
export class HomeComponent {

  constructor(){
    
  }

}

<div class="w3-container w3-margin-top">
    <h1>Hello, world!</h1>
    <p>Welcome to this base project prototype</p>
    <p>This project is built with:</p>
    <ul>
      <li><a href='https://get.asp.net/'>ASP.NET Core</a> and <a href='https://msdn.microsoft.com/en-us/library/67ef8sbd.aspx'>C#</a> for cross-platform server-side code</li>
      <li><a href='https://angular.io/'>Angular</a> and <a href='http://www.typescriptlang.org/'>TypeScript</a> for client-side code</li>
      <li><a href='https://www.w3schools.com/w3css/default.asp'>w3css</a> for layout and styling</li>
    </ul>
    <p>This is a simple app that creates new users and list them all if you are logged in. You can start by creating a new User</p>
    <p>The <code>AngularApp</code> subdirectory is a standard Angular CLI application. If you open a command prompt in that directory, you can run any <code>ng</code> command (e.g., <code>ng test</code>), or use <code>npm</code> to install extra packages into it.</p>
</div>

// react-app/src/components/home/Home.tsx
import React from "react";

export class Home extends React.Component{
    render(){
        return(
            <div className="w3-container w3-margin-top">
                <h1>Hello, world!</h1>
                <p>Welcome to this base project prototype</p>
                <p>This project is built with:</p>
                <ul>
                <li><a href='https://get.asp.net/'>ASP.NET Core</a> and <a href='https://msdn.microsoft.com/en-us/library/67ef8sbd.aspx'>C#</a> for cross-platform server-side code</li>
                <li><a href='https://reactjs.org/'>React</a> and <a href='https://www.typescriptlang.org/docs/handbook/react.html'>TypeScript</a> for client-side code</li>
                <li><a href='https://www.w3schools.com/w3css/default.asp'>w3css</a> for layout and styling</li>
                </ul>
                                
                <p>This is a simple app that creates new users and list them all if you are logged in. You can start by creating a new User</p>                
            </div>
            );
    }
}
